# Generated by Django 5.2.3 on 2025-06-24 15:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the amenity (e.g., 'Extra Towels', 'Toothbrush').", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the amenity.')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional: Price of the amenity.', max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the hotel.', max_length=255, unique=True)),
                ('api_key', models.CharField(blank=True, help_text='API key for AI services specific to this hotel (optional).', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
            },
        ),
        migrations.CreateModel(
            name='GuestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(help_text='The room number where the request was made.', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the request was made.')),
                ('raw_text', models.TextField(help_text="The raw transcribed text of the guest's request.")),
                ('ai_intent', models.CharField(help_text='The intent recognized by the AI.', max_length=100)),
                ('ai_entities', models.JSONField(default=dict, help_text="JSON representation of entities extracted by the AI (e.g., {'amenity': 'towel', 'quantity': 1}).")),
                ('conci_response_text', models.TextField(help_text='The text response Conci gave to the guest.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the guest request.', max_length=20)),
                ('staff_notes', models.TextField(blank=True, help_text='Notes added by hotel staff regarding the request.')),
                ('last_updated_by_staff', models.DateTimeField(auto_now=True, help_text='Timestamp of the last status update by staff.')),
                ('hotel', models.ForeignKey(help_text='The hotel where this request originated.', on_delete=django.db.models.deletion.CASCADE, related_name='guest_requests', to='main.hotel')),
            ],
            options={
                'verbose_name': 'Guest Request',
                'verbose_name_plural': 'Guest Requests',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HotelConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Configuration key (e.g., 'wifi_password', 'checkout_time').", max_length=100)),
                ('value', models.TextField(help_text='Configuration value.')),
                ('hotel', models.ForeignKey(help_text='The hotel this configuration belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='main.hotel')),
            ],
            options={
                'verbose_name': 'Hotel Configuration',
                'verbose_name_plural': 'Hotel Configurations',
                'unique_together': {('hotel', 'key')},
            },
        ),
    ]
