# Generated by Django 5.2.3 on 2025-06-27 09:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={},
        ),
        migrations.AlterModelOptions(
            name='guestrequest',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={},
        ),
        migrations.AlterField(
            model_name='amenity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='guestrequest',
            name='ai_entities',
            field=models.JSONField(blank=True, default=dict, help_text="AI-extracted entities (e.g., {'item': 'towel', 'quantity': 2})", null=True),
        ),
        migrations.AlterField(
            model_name='guestrequest',
            name='ai_intent',
            field=models.CharField(blank=True, help_text='AI-detected intent (e.g., request_amenity, get_info)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guestrequest',
            name='conci_response_text',
            field=models.TextField(blank=True, help_text="Conci's full conversational response to the guest.", null=True),
        ),
        migrations.AlterField(
            model_name='guestrequest',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_requests', to='main.hotel'),
        ),
        migrations.AlterField(
            model_name='guestrequest',
            name='last_updated_by_staff',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guestrequest',
            name='raw_text',
            field=models.TextField(help_text='The original raw text request(s) from the guest.'),
        ),
        migrations.AlterField(
            model_name='guestrequest',
            name='room_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='guestrequest',
            name='staff_notes',
            field=models.TextField(blank=True, help_text='Notes added by staff regarding this request.', null=True),
        ),
        migrations.AlterField(
            model_name='guestrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='guestrequest',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='api_key',
            field=models.CharField(blank=True, help_text='Optional API key for external integrations if needed per hotel.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='hotelconfiguration',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='main.hotel'),
        ),
        migrations.AlterField(
            model_name='hotelconfiguration',
            name='key',
            field=models.CharField(help_text="e.g., 'checkout_time', 'wifi_password'", max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelconfiguration',
            name='value',
            field=models.TextField(help_text='The configuration value.'),
        ),
        migrations.CreateModel(
            name='GuestRoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(help_text='The physical room number or identifier.', max_length=10)),
                ('guest_names', models.TextField(blank=True, help_text='Names of all guests assigned to this room (e.g., comma-separated).', null=True)),
                ('check_in_time', models.DateTimeField(help_text='Actual or scheduled check-in date and time.')),
                ('check_out_time', models.DateTimeField(help_text='Actual or scheduled check-out date and time.')),
                ('bill_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total bill amount for this assignment.', max_digits=10)), # type: ignore
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid by the guest so far.', max_digits=10)), # type: ignore
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to='main.hotel')),
            ],
            options={
                'ordering': ['-check_in_time'],
                'unique_together': {('hotel', 'room_number', 'check_in_time')},
            },
        ),
    ]
