# Generated by Django 5.2.3 on 2025-07-15 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_hotel_total_rooms_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amenity',
        ),
        migrations.AlterModelOptions(
            name='hotelconfiguration',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='guestroomassignment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='guestrequest',
            name='last_updated_by_staff',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='guestrequest',
            name='ai_entities',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='guestrequest',
            name='ai_intent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guestrequest',
            name='conci_response_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guestrequest',
            name='raw_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='guestrequest',
            name='staff_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guestroomassignment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='guestroomassignment',
            name='bill_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='guestroomassignment',
            name='check_in_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='guestroomassignment',
            name='check_out_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='guestroomassignment',
            name='guest_names',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guestroomassignment',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_assignments', to='main.hotel'),
        ),
        migrations.AlterField(
            model_name='guestroomassignment',
            name='room_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='total_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotelconfiguration',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelconfiguration',
            name='value',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.hotel'),
        ),
    ]
