# Generated by Django 5.2.3 on 2025-07-19 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_userprofile_hotel_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestroomassignment',
            options={'ordering': ['check_in_time']},
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='request_type',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('repairs', 'Repairs'), ('housekeeping', 'Housekeeping'), ('room_service', 'Room Service'), ('concierge', 'Concierge'), ('general_inquiry', 'General Inquiry'), ('casual_chat', 'Casual Chat')], default='general_inquiry', help_text='Categorized type of the guest request.', max_length=50),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guestrequest',
            name='ai_entities',
            field=models.JSONField(blank=True, help_text='JSON representation of entities extracted by AI.', null=True),
        ),
        migrations.AlterField(
            model_name='guestrequest',
            name='ai_intent',
            field=models.CharField(blank=True, help_text="AI's determined intent of the request.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='guestrequest',
            name='chat_history',
            field=models.JSONField(blank=True, help_text='Full JSON chat history for this specific request.', null=True),
        ),
        migrations.AlterField(
            model_name='guestrequest',
            name='conci_response_text',
            field=models.TextField(blank=True, help_text='The response sent by Conci to the guest.', null=True),
        ),
        migrations.AlterField(
            model_name='guestrequest',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_requests', to='main.hotel'),
        ),
        migrations.AlterField(
            model_name='guestrequest',
            name='raw_text',
            field=models.TextField(help_text='The original raw text message from the guest.'),
        ),
        migrations.AlterField(
            model_name='guestrequest',
            name='staff_notes',
            field=models.TextField(blank=True, help_text='Internal notes added by staff regarding this request.', null=True),
        ),
        migrations.AlterField(
            model_name='guestroomassignment',
            name='guest_names',
            field=models.TextField(help_text='Full names of guests, separated by commas if more than one.'),
        ),
        migrations.AlterField(
            model_name='guestroomassignment',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_assignments', to='main.hotel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='main.hotel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('cleaning', 'Cleaning Required'), ('maintenance', 'Under Maintenance'), ('out_of_service', 'Out of Service')], default='available', max_length=20),
        ),
    ]
