# Generated by Django 5.2.3 on 2025-07-19 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_guestroomassignment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Cost per unit of this amenity.', max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='guestroomassignment',
            name='bill_amount',
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='amenity_quantity',
            field=models.IntegerField(default=1, help_text='Quantity of the amenity requested.'),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='bill_added',
            field=models.BooleanField(default=False, help_text="True if the amenity cost has been added to guest's bill."),
        ),
        migrations.AddField(
            model_name='guestroomassignment',
            name='base_bill_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Base room charges for the stay.', max_digits=10),
        ),
        migrations.AddField(
            model_name='guestroomassignment',
            name='total_bill_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total bill including room charges and amenities.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='guestrequest',
            name='request_type',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('repairs', 'Repairs'), ('housekeeping', 'Housekeeping'), ('room_service', 'Room Service'), ('concierge', 'Concierge'), ('amenity_request', 'Amenity Request'), ('general_inquiry', 'General Inquiry'), ('casual_chat', 'Casual Chat')], default='general_inquiry', help_text='Categorized type of the guest request.', max_length=50),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='amenity_requested',
            field=models.ForeignKey(blank=True, help_text='The amenity requested, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.amenity'),
        ),
    ]
