# Generated by Django 5.2.3 on 2025-07-23 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_amenity_remove_guestroomassignment_bill_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestroomassignment',
            name='room_number',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=1000),
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('housekeeping', 'Housekeeping'), ('maintenance', 'Maintenance'), ('concierge', 'Concierge'), ('front_desk', 'Front Desk'), ('room_service', 'Room Service'), ('general_inquiry', 'General Inquiry'), ('amenity_request', 'Amenity Request'), ('general', 'General/All')], default='general', help_text='Category of staff member, defines types of requests they can handle.', max_length=50)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='main.hotel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['user__username'],
            },
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, help_text='The staff member assigned to handle this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='main.staffmember'),
        ),
    ]
